# Generated by Django 4.1.7 on 2023-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
